using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GeradorDeRecortes
{
    public class Biblioteca
    {
        private readonly string[] textos =
        {
            "Parecia uma semana como nos tempos (gloriosos) das Copas do Mundo de Bebeto e Romário, com hora marcada para se juntar, olhar a televisão e, antes disso, muito \"zap\", especulando, trocando, torcendo, imaginando, e até sonhando novos sonhos. Uma semana forjada na expectativa pelas entrevistas do \"Jornal Nacional\" com os presidenciáveis. Que oportunidade preciosa para o eleitor em cada realidade de Brasil pensar sobre o país onde o pedido de Ruth de Aquino ainda existe. Precisa existir. Mas até quando? Quem acompanha Ruth nisso? O pedido de perdão de Ruth de Aquino é de quem mais",
            "A empresária Zilu Godoi retornou às redes sociais na última quinta-feira, 24, e explicou para os seus seguidores por que estava sumida. A ex-mulher do cantor Zezé Di Camargo também falou sobre o aparente inchaço no seu rosto. “Muita gente perguntando o porquê estou sumida dos stories e das fotos. Meus amores, eu fiz uma pequena cirurgia de dente do siso. E não é que o negócio aqui me deixou mais inchada do que vocês possam imaginar?! Mas querem saber o que realmente importa? É a felicidade, que não cabe no meu peito”, escreveu na em um post no Instagram. Zilu falou que o motivo da sua felicidade é que seu filho, Igor Ci, e sua nora, Amabylle, estão na casa dela em Orlando, nos Estados Unidos. Ela mostrou que estava celebrando com a família o feriado americano de Ação de Graças e também assistindo ao primeiro jogo do Brasil na Copa do Mundo do Catar. “Com companhias que tanto amo! Por isso resolvi compartilhar com vocês este momento tão especial, totalmente desprendida se estou bem na foto ou não, pois o que realmente importa é esse amor visceral que só quem é mãe vai entender”, declarou a empresária. A atriz Camilla Camargo, filha de Zilu, deixou um comentário no post: O que importa é você bem e feliz! Te amo demais",
            "A modelo Juliana Nehme conseguiu embarcar em um voo com destino a Doha, no Catar, na tarde desta quinta-feira, 24. O caso da brasileira ganhou repercussão após ela relatar nas redes sociais que na última terça-feira, 22, foi impedida de embarcar em um voo no Líbano por ser “muito gorda”. “Tudo aconteceu muito rápido. Estava na casa da embaixada e disseram que eu tinha que vir ao aeroporto. A Qatar finalmente cedeu e eles aceitaram que eu fizesse a viagem, eu e minha mãe, do jeito que eu comprei, sem ter que pagar a multa e sem eu ter que pagar o assento extra”, disse a modelo nos stories do Instagram. Conforme Juliana relatou anteriormente, a companhia aérea informou que ela só poderia fazer a viagem se comprasse dois assentos ou se trocasse a passagem da classe econômica para a executiva. Após expôs o caso virtualmente, ela recebeu ajuda do embaixador do Brasil no Líbano. Já dentro do avião, a modelo disse que passará quatro horas no voo até Doha e de lá pegará outro voo com destino a São Paulo. “Gostaria de agradecer todo mundo que me ajudou. Não tenho palavras, não tenho como agradecer. Vou orar por cada um”, afirmou a brasileira visivelmente emocionada. “Quanto às acusações de que fui grossa e briguei com as atendentes, é mentira! Estão tentando camuflar o que fizeram comigo",
            "Você com certeza já ouviu a música What A Feeling, certo? O hit era um clássico dos anos 1980 e fez parte da trilha sonora de diversos filmes da época, incluindo Flashdance. Irene Cara, a cantora por trás do êxito, morreu na última sexta-feira, dia 25, aos 63 anos de idade.\r\n\r\nDe acordo com a notícia divulgada nas redes sociais da própria artista, Cara estava em sua casa, na Flórida, Estados Unidos, quando deu o último suspiro.\r\n\r\nAs causas da morte permanecem desconhecidas e vão ser divulgadas quando houver informação disponível. Esta é a pior parte de ser publicist. Não acredito que tive de escrever isto, muito menos revelar a notícia, escreveu Judith A. Moose, a responsável por gerenciar a carreira de Irene.\r\n\r\nOs fãs de Chaves também foram surpreendidos pela morte de Héctor Bonilla. Aos 83 anos de idade, ele batalhava há quatro anos contra um câncer renal. No Brasil, o ator era conhecido por interpreta a si mesmo no seriado mexicano.\r\n\r\nSabemos que Héctor deixou um legado imensurável e que muitos corações lamentarão sua morte. Saiba que, apesar da tristeza infinita que nos assola, estamos tranquilos de nos despedir de um homem que partiu sem dever nada a ninguém, viveu intensa e plenamente, que pregou sempre com exemplo e semeou alegria e amor a cada caminho que percorreu. O show acabou, não brinque. Quem me viu, viu. Nada está errado, dizia o comunicado feito pela família",
            "A Audi anuncia a chegada ao mercado brasileiro do Q5 híbrido TFSIe, disponível na opção SUV com preços a partir de R$ 413.990 e Sportback partindo de R$ 443.990 – na modalidade venda direta. Serão ao todo quatro versões, sendo duas com cada carroceria: Performance e Performance Black, que adiciona acabamentos em preto no exterior.\r\n\r\nImportado do México, o Q5 híbrido se soma então aos quatro modelos eletrificados já oferecidos hoje pela Audi no mercado nacional: e-tron, e-tron Sportback, e-tron Sportback S, RS e-tron GT. Essa linha conta com 42 concessionárias em todo o país. Na Europa, a novidade é comercializada desde o início do ano passado",
            "Lesão na terceira vértebra em 2014, fratura no quinto metatarso em 2018 e uma lesão ligamentar no tornozelo em 2022… A estreia do Brasil contra a Sérvia confirmou uma sina de lesões de Neymar em Copas do Mundo. Em sua terceira participação na competição, o camisa 10 sofre outra vez um problema físico. A CBF confirmou que o jogador não atuará na próxima partida, contra a Suíça, na segunda-feira (28). Existe a possibilidade ainda de o atleta perder também o jogo contra Camarões, já na sexta.\r\n\r\nNeymar foi levado para fazer exames de imagem na manhã da última sexta em Doha, no Catar, e teve detectados uma lesão ligamentar no tornozelo direito e um edema ósseo. Na avaliação do médico da seleção brasileira, Rodrigo Lasmar, o ideal é não fazer avaliações precipitadas e tratar a questão dia após dia.",
            "Para a sua primeira Copa do Mundo, em casa, diante de sua torcida, o então jogador do Barcelona chegou com duas lesões importantes ao longo do ano. Neymar havia sofrido uma lesão no tornozelo direito (o mesmo de agora) e uma no pé esquerdo. O pior, no entanto, ainda estava por vir. Nas quartas de final, contra a Colômbia, o jogador levou uma joelhada de Zuniga, aos 41 minutos do segundo tempo, e teve uma fratura na terceira vértebra da lombar. Era o fim do Mundial para o jogador, que não pôde atuar no 7 a 1 para a Alemanha nem na disputa de terceiro lugar contra a Holanda.\r\n\r\nQuatro anos mais tarde, Neymar teve outra séria lesão em sua carreira, ficou três meses sem jogar e só voltou a atuar semanas antes da Copa na Rússia. O jogador levou um pisão no pé direito, em partida do Paris Saint-Germain contra o Olympique de Marseille, e teve de passar por cirurgia. A longa recuperação não devolveu o camisa 10 em plenas condições de fazer grandes atuações. Junto a isso, o jogador foi bastante criticado por simular ou exagerar nas reações às faltas recebidas.",
            "O repolho refogado é uma excelente opção de acompanhamento saudável, leve e delicioso para suas refeições. Essa maravilha que também leva pedacinhos de tomates, pimentão e milho verde é diferente, bem fácil e rápido de preparar e com certeza todos vão gostar. Então não perca tempo, confira a receita, e faça hoje mesmo o sensacional repolho refogado que será um sucesso em sua casa! Para a receita de repolho refogado, que é bem simples de fazer, os ingredientes necessários são: repolho, ervilhas, milho-verde, tomates, pimentão vermelho, alho, azeite, cheiro-verde, sal e pimenta-do-reino. Primeiramente iremos higienizar o repolho, cortá-lo em tiras finas e reservar. Depois vamos tirar as sementes e cortar o pimentão e os tomates em tiras. Finalmente vamos refogar tudo em uma panela com azeite e em seguida temperar com cheiro-verde, sal e pimenta-do-reino a gosto. Você já pode servir e apreciar seu maravilhoso repolho refogado, aproveite!",
            "Muitos programadores experientes vão entender bem sobre o que estou falando, alguns irão discordar, afinal, cada programador tem a sua maneira de enxergar os códigos. Mas para você que é novo neste mundo tenha em mente que programar é uma tarefa difícil que só se aprende com muitas horas de prática e persistência. Nada de sonhar com salários altos em 6 meses de estudo pois até você conseguir um salário bacana, terá que ralar muito. Então vamos lá:\r\n\r\n• Sua saúde mental está em risco. Burnout não é brincadeira, está é uma área super estressante por si só, com prazos apertados e longos períodos de jornada de trabalho.\r\n\r\n• Não existe bug simples. Um erro estúpido como esquecer um ponto e vírgula ou escrever errado o nome de uma variável pode facilmente levar uma semana para encontrar e consertar e pode causar uma perda de sono significativa.\r\n\r\n• Tudo o que você aprende hoje em cursos, você terá que aprender de novo quando estiver trabalhando em um projeto de verdade.\r\n\r\n• Conforme seu salário for aumentando e você for evoluindo, as responsabilidades e as cobranças também aumentarão. Isso pode prejudicar a tua qualidade de vida.\r\n\r\n• Você vai ter que dedicar um bom tempo de estudo depois (ou antes) do trabalho para conseguir evoluir.\r\n\r\n• É bobagem virar a noite programando. Algumas pessoas funcionam melhor pela manhã ou a tarde, mas vai do ritmo de cada um.\r\n\r\n• Programar pode viciar. Eu não consigo ver um app, jogo ou site sem visualizar mentalmente como o código deve parecer.\r\n\r\n• Você terá que estudar o resto da vida para se manter no mercado de trabalho.\r\n\r\nLembre-se que estas verdades não se aplicam a todas as pessoas, existem muitos sortudos fora da curva, mas provavelmente você não é uma delas. Programe por amor",
            "Conheça o método para criar Dashboards incríveis usando apenas Python",
            "Os termos relacionados com a economia\r\ntêm invadido as conversas do dia a dia e\r\ntornaram-se parte da linguagem geral.\r\n",
            "Bom dia tropa, bom domingo",
            "aspetodAO n.m. 1 feição que um objeto ou uma pessoa\r\napresenta à vista; aparência 2 semblante; fisionomia\r\n3 lado; face; ângulo 4 ponto de vista 5 LINGUÍSTICA categoria\r\ngramatical que exprime a forma como uma situação é\r\nperspetivada na sua estrutura temporal interna, a partir\r\nde um ponto de referência temporal (Do lat. aspectu-,\r\n«vista de olhos») ACORDO ORT grafia anterior: aspecto\r\ncontável adj.2g. 1 que se pode contar 2 que pode ser\r\nnarrado 3  GRAMÁTICA diz‑se do nome que designa um con‑\r\njunto que se pode decompor em partes singulares que se\r\npodem enumerar (De contar+-vel)\r\ncorreferênciadAO n.f. LINGUÍSTICA relação existente entre\r\ndois ou mais termos que referem a mesma entidade (cor‑\r\nreferente) ACORDO ORT grafia anterior: co-referência\r\ntransitivo-predicativo [z] adj. GRAMÁTICA diz‑se do\r\nverbo que seleciona um complemento direto e um predi‑\r\ncativo do complemento direto (é o caso do verbo achar\r\nna frase: Achei­‑a muito simpática.)\r\ntruncação n.f. 1  LINGUÍSTICA processo através do qual é\r\nformada uma palavra a partir da eliminação de parte da\r\npalavra de que deriva 2 LINGUÍSTICA palavra que resulta desse\r\nprocesso (De truncar+-ção)",
            "Os termos da gramática da língua portuguesa\r\ntêm vindo a mudar. Conheça os vocábulos\r\nque explicam a forma como a língua funciona.\r\n",
            "body pump n.m. modalidade aeróbica em que se utili‑\r\nzam barras e pesos, sincronizados com música, sob a\r\norientação de professores (Do ing. body pump®, «id.»)\r\nfull-contact n.m. DESPORTO desporto de combate que\r\ncombina várias artes marciais, associando os golpes do\r\nboxe aos chutos do karaté, e em que os praticantes usam\r\ndiversas proteções (luvas, capacete, botas) devido ao\r\nconstante contacto físico (Do ing. full‑contact (karate), «id.»)\r\npetanca n.f. DESPORTO jogo praticado em zonas planas e\r\narenosas por equipas cujo número de jogadores pode\r\nvariar, e que consiste no lançamento de um conjunto de\r\nbolas metálicas que deverão ficar o mais perto possível de\r\numa pequena bola de madeira, lançada previamente (Do\r\nfr. pétanque, «id.»)\r\ntrekking n.m. desporto radical, com vários níveis de\r\ndificuldade, que consiste em fazer longas caminhadas em\r\nterrenos acidentados ou montanhosos, pernoitando ao\r\nrelento em locais que integram o itinerário (Do ing. trek‑\r\nking, «id.»)\r\nskimboard n.m. desporto aquático que consiste em\r\nlançar‑se em corrida sobre uma prancha na areia molhada\r\nou em águas baixas (Do ing. skimboard, «id.»)",
            "A diversidade cada vez maior de atividades\r\nfísicas e desportivas leva-nos a conhecer\r\nnovos termos.",
            "biodiesel n.m. combustível renovável e biodegradável,\r\nfabricado a partir do óleo vegetal obtido de sementes\r\noleaginosas e/ou de óleos vegetais, usado em veículos\r\ncom motor diesel (De bio-+diesel)\r\necoeficiência n.f. estratégia de gestão que combina\r\neficiência económica e ecológica, no sentido de produzir\r\nmais com menos recursos, menos resíduos e menos riscos\r\n(De eco-+eficiência)\r\npegada2\r\n [pÈ] n.f. 1 vestígio que o pé deixa impresso no\r\nsolo 2 ⌈fig.⌋ sinal; vestígio; ~ de carbono quantidade de dió‑\r\nxido de carbono libertado para a atmosfera como resul‑\r\ntado das atividades diárias de uma pessoa, organização ou\r\ncomunidade, calculada durante um determinado período;\r\n~ ecológica quantidade de terra e água necessária para\r\nmanter o estilo de vida de uma pessoa ou de uma popu‑\r\nlação, calculada com base nos recursos consumidos por\r\nessa pessoa ou grupo no seu dia a dia e pelos resíduos que\r\nproduz (Do lat. *pedicata-, de pede-, «pé»)\r\nsinecologia n.f. área da ecologia que estuda as rela‑\r\nções entre as comunidades de organismos vivos e o",
            "Os termos relacionados com as questões\r\nambientais e ecológicas estão muito presentes no dia a dia dos falantes.",
            "biodisponibilidade n.f. FARMÁCIA grau e velocidade\r\ncom que o princípio ativo de uma substância é absorvido\r\npelo organismo, tornando‑se disponível para atuar da\r\nforma desejada (De bio-+disponibilidade)\r\nholter n.m. 1 MEDICINA dispositivo portátil que faz a moni‑\r\ntorização do ritmo cardíaco durante a atividade diária\r\nnormal do indivíduo, habitualmente por um período de\r\n24 horas, cujo objetivo é avaliar a presença de arritmias\r\ncardíacas e/ou outras anomalias relacionadas com o fun‑\r\ncionamento do coração 2 MEDICINA exame médico realizado\r\ncom esse dispositivo (De N. J. Holter, antr., biofísico que\r\ninventou o dispositivo)\r\nnomofobia n.f. receio exagerado e inexplicável de ficar\r\nincontactável por não se ter um telemóvel ou dispositivos\r\nsemelhantes para comunicar (Do ing. nomophobia, «id.»,\r\nde no+mo(bile)+phobia)\r\nresveratrol n.m. QUÍMICA substância existente nas uvas\r\npretas, no vinho tinto, nos amendoins e em certas plan‑\r\ntas, e que apresenta propriedades antioxidantes e anti‑",
            "Os domínios técnicos e científicos evoluem\r\nmuito rapidamente e são responsáveis pela\r\nintrodução de variadíssimos neologismos.",
            "carpaccio n.m. CULINÁRIA prato de culinária geralmente\r\nservido como entrada, composto de fatias muito finas de\r\ncarne ou peixe cruas, temperado com azeite, sumo de\r\nlimão ou outros molhos, por vezes acompanhado de\r\nqueijo ralado (Do it. carpaccio, «id.»)\r\nmacaron n.m. pequeno doce arredondado, à base de\r\npasta de amêndoas, clara de ovo e açúcar, que possui\r\nrecheio e pode apresentar diversos sabores (baunilha,\r\ncafé, chocolate, etc.) (Do fr. macaron, «id.»)\r\nnigiri n.m. CULINÁRIA prato japonês que consiste num\r\nbolinho de arroz cozido, avinagrado e doce, coberto por\r\num pedaço de peixe cru ou fruto do mar\r\nsashimi n.m. CULINÁRIA prato japonês que consiste em\r\nfatias finas de peixe ou marisco crus, geralmente acom‑\r\npanhado por nabo ralado e servido com molho (Do jap.)\r\nwrap n.m. CULINÁRIA alimento que consiste numa massa\r\nmuito fina à base de farinha, que se enrola sobre si\r\nmesma, com vários tipos de recheio (Do ing. wrap, ",
            "Com a globalização e o fácil acesso à informação, somos influenciados por outras\r\nculturas na culinária. ",
            "contingentação n.f. ECONOMIA prática protecionista que\r\nconsiste na restrição das importações de determinados\r\nprodutos ou de produtos de determinadas origens pelo\r\nestabelecimento de quotas (De contingente+-ção)\r\npostecipado adj. ECONOMIA designativo do juro pago no\r\nfim do respetivo período de contagem (De pos-+(an)-\r\ntecipado)\r\nrating n.m. avaliação da credibilidade e da capacidade\r\nde cumprimento das responsabilidades financeiras de\r\numa entidade feita por uma empresa especializada ou\r\npor um grupo de especialistas (Do ing. rating, «id.»)\r\nspin-off n.m. ECONOMIA empresa nova criada para explorar\r\nprodutos ou serviços tecnológicos ou inovadores, concebida\r\na partir de um grupo de pesquisa ou centro de investigação\r\nde uma outra organização já existente, que a apoia no seu\r\ndesenvolvimento (Do ing. spin-off, «id.»)\r\ntóxico [tóksi] adj.,n.m. 1 que ou substância que produz\r\nefeitos nocivos no organismo 2 que ou substância que\r\ncontém veneno ■ adj. 1 ECONOMIA diz‑se da dívida com alto\r\nrisco de não ser paga 2 ECONOMIA diz‑se do ativo cujo valor\r\nde transação não representa o seu valor real (Do gr. toxi",
            "amigabilidade n.f. 1 qualidade ou carácter do que é\r\namigável 2 INFORMÁTICA característica de um produto (pro‑\r\ngrama, página de internet, etc.) que é fácil de aprender a\r\nusar (De amigável+-i-+-dade)\r\nbluetooth n.m. INFORMÁTICA tecnologia de transmissão de\r\ndados sem fios, que efetua a ligação de dispositivos ele‑\r\ntrónicos próximos entre si (Do ing. Bluetooth®)\r\ncomputação n.f. 1 ato ou efeito de computar; cálculo;\r\ncontagem 2 cálculo orçamental 3 INFORMÁTICA tratamento de\r\ndados, de informação, através de um computador; ~ em\r\nnuvem sistema em que os recursos (informação, software,\r\nbases de dados, etc.) estão disponíveis em servidores remo‑\r\ntos, podendo ser acedidos pelos utilizadores através da inter‑\r\nnet (Do lat. computatiōne-, «cálculo»)\r\nripar2 v.tr. extrair e converter o conteúdo (música, fil‑\r\nmes) de um CD/DVD para o disco duro num formato\r\ndiferente do original, em que a informação está mais\r\ncompactada mas mantém a mesma qualidade (Do ing.\r\n(to) rip, «id.»)\r\nsmartphone n.m. telemóvel com características semelhantes às de um computador pessoal (agenda eletrónica,\r\nacesso à internet e a e‑mail, câmara fotográfica, etc.);\r\ntelefone inteligente (Do ing. smartphone, «id.»)",
            "A informática é uma das áreas que mais tem\r\nevoluído, trazendo para a língua portuguesa\r\nimensos neologismos.\r\n",
            "A língua portuguesa está em constante\r\nevolução. Todos os dias, criamos e utilizamos novos sentidos e novos vocábulos. ",
            "balcanizar v.tr. 1 dividir (região, país) em zonas mais\r\npequenas e geralmente hostis entre si 2 dividir; fragmentar\r\n(De Balcãs, top.+-izar)\r\ncriopreservar v.tr. conservar (material biológico, como\r\ncélulas estaminais, sangue, etc.) através do congelamento\r\na temperaturas muito baixas (geralmente 196 °C negati‑\r\nvos) (De crio-+preservar)\r\ncultivar2 n.m. BOTÂNICA variedade de planta cultivada que,\r\na partir de uma espécie natural, é submetida a melhora‑\r\nmento genético, apresentando características perfeita‑\r\nmente identificáveis que a distinguem de outras varieda‑\r\ndes (Do ing. cultivar, «id.», de culti(vated)+var(iety))\r\ncustomização n.f. adaptação de produtos, configu‑\r\nrações ou serviços a gosto ou às necessidades do utiliza‑\r\ndor; personalização (De costumizar+-ção)\r\nfacebookiano adj. relativo à rede social de nome\r\nFacebook ■ adj.,n.m. que ou pessoa que é membro dessa\r\nrede social (De Facebook+-iano)\r\ngostador adj.,n.m. que ou pessoa que gosta de algo ou\r\nalguém, especialmente no contexto da internet e das \r\n",
            "brincos-de-princesa n.m.pl. 1  BOTÂNICA planta orna‑\r\nmental, da família das Enoteráceas, de flores pendentes\r\navermelhadas ou cor‑de‑rosa 2 BOTÂNICA flor dessa planta\r\ncão-da-pradaria n.m. ZOOLOGIA designação comum aos\r\nmamíferos roedores e escavadores da família dos esquilos,\r\nde pelo castanho‑claro, corpo robusto e cauda e pernas\r\ncurtas, que vivem em colónias subterrâneas nas planícies\r\nda América do Norte\r\nautóctone adj.,n.2g. que ou pessoa que nasceu na pró‑\r\npria terra em que habita; aborígene; indígena ■ adj.2g.\r\ndesignativo da primeira língua falada num país (Do gr.\r\nautókhthon, «indígena», pelo lat. autochtŏne-, «id.»)\r\negípcio adj. relativo ou pertencente ao Egito ■ n.m. natu‑\r\nral ou habitante do Egito (Do lat. aegyptĭu-, «egípcio»)\r\nsucção n.f. 1  ato ou efeito de sugar ou de chupar\r\n2 absorção 3 ⌈fig.⌋ extorsão 4 ⌈fig.⌋ exploração (Do lat. tard.\r\nsuctiōne-, pelo fr. succion, «id.»)\r\ntransepto [s] n.m. corpo transversal de uma igreja, que\r\nse estende para um e outro lado da nave, formando com\r\nela uma cruz (Do ing. transept, «id.»)",
            "Os hífenes mantêm-se nas palavras que\r\ndesignam espécies botânicas ou zoológicas.\r\nSe pronunciadas, as consoantes c e p são\r\nmantidas.",
            "jiboiadAO n.f. ZOOLOGIA grande serpente, da família dos\r\nBoídeos, não venenosa, geralmente de cor acinzentada,\r\nque se alimenta de roedores e de aves e vive na América\r\ndo Sul (Do tupi yi’mboya, «cobra das rãs») ACORDO ORT gra‑\r\nfia anterior: jibóia\r\njibóia n.f. ⇒ jiboiadAO\r\nmaio n.m. 1 quinto mês do ano civil, com trinta e um\r\ndias 2  ⌈fig.⌋ tempo das flores; primavera 3  ⌈fig.⌋ indivíduo\r\nmuito garrido ■ adj. relativo ao mês de maio (Do lat.",
            "fim-de-semana n.m. fim de semanad fim de semanadAO n.m. período em que geralmente\r\nnão se trabalha, e que decorre desde sexta‑feira à noite até\r\ndomingo à noite ACORDO ORT grafia anterior: fim­‑de­‑semana",
            "adoção 1 ato ou efeito de adotar 2 DIREITO criação,\r\npor sentença judicial, de um vínculo jurídico semelhante ao\r\nque resulta da filiação natural, independentemente dos\r\nlaços de sangue; filiação legal 1 aprovação (de doutrina,\r\nlei, etc.) 4  aceitação (de ideia, sugestão, etc.) (Do lat.\r\nadoptiōne-, «id.») ACORDO ORT grafia anterior: adopção\r\nadopção n.f. ⇒ adoçãodAO",
            "O Dicionário Editora da Língua Portuguesa 2013 é o dicionário mais completo da variedade europeia do português.",
            "O Acordo Ortográfico visa unificar a ortografia do português, reduzindo as diferenças existentes nas normas ortográficas\r\noficiais. ",
            "• Cerca de 265 000 definições, expressões\r\nfixas e provérbios\r\n• Atualizado com o Acordo Ortográfico,\r\nregistando as grafias novas e conservando\r\nas grafias anteriores a esta reforma\r\npara facilitar a pesquisa dos vocábulos\r\n• Vocabulário geral, técnico e científico,\r\nincluindo a nova terminologia gramatical\r\ndos programas de português (Dicionário\r\nTerminológico)\r\n• Diversos anexos: Guia do Acordo\r\nOrtográfico; Abreviaturas, siglas\r\ne símbolos; Expressões estrangeiras",
            "Estamos preparando um super buffet natalino para você celebrar junto com a sua família a noite de natal… faça já sua reserva e garanta sua mesa",
            "é psicanalista, mestra em Filosofia pela PUC-SP, doutoranda pela Unicamp e professora. Se você se interessa por filosofia e psicanálise, sugerimos que siga a sua página",
            "No livro eu faço você aprender a errar desde o momento da compra. Esqueça os erros do passado. Planeje os erros do futuro. É simples, os erros, falhas, fracassos do passado não irão mudar. Porém, eles são uma base de conhecimento que você irá utilizar para errar cada vez melhor. Aprenda a Fracassar melhor, otimize seu tempo, otimize suas frustrações e decepções. É errando que se aprende a errar. A vida é uma coleção de erros, e você é um excelente colecionador. Saia da sua zona de conforto para fracassar em áreas antes não exploradas. Todo mundo duvida de você, junte-se a eles. Hoje você é definido pelas suas escolhas, limitações, derrotas, falhas e fracassos. Amanhã você será definido da mesma forma. Só que hoje será melhor do que amanhã. A sua incapacidade de mudar o passado é o que te faz extremamente capaz de estragar o seu futuro. Vai lá! Sai da sua zona de conforto e quebra a cara",
        };

        public string GerarPalavra(int tamanhoMaximo, int tamanhoMinimo, bool somenteMaiscula)
        {
            var palavras =  String.Join(" ", textos.Select(item => Formata(item)).Distinct().ToArray()).Split(" ");

            var palavrasFiltradas = new List<string>();

            foreach (var item in palavras)
            {
                bool deveAdicionar = true;
                if(tamanhoMaximo > 0 && item.Length > tamanhoMaximo)
                {
                    deveAdicionar = false;
                }

                if (tamanhoMinimo > 0 && item.Length < tamanhoMinimo)
                {
                    deveAdicionar = false;
                }

                if (deveAdicionar)
                {
                    palavrasFiltradas.Add(item);
                }
            }

            var indice = new Random().Next(palavrasFiltradas.Count - 1);
            return somenteMaiscula == false? palavrasFiltradas[indice] : palavrasFiltradas[indice].ToUpper();
        }

        private string Formata(string text)
        {
            var SEPARADOR = string.Empty;
            var SEPARADOR_ESPACO = " ";
            return text.Replace("[", SEPARADOR).Replace("]", SEPARADOR).Replace("+", SEPARADOR).Replace("»", SEPARADOR).Replace("«", SEPARADOR).Replace(";", SEPARADOR).Replace("•", SEPARADOR).Replace(",", SEPARADOR).Replace(".", SEPARADOR).Replace("(", SEPARADOR).Replace(")", SEPARADOR).Replace("”", SEPARADOR).Replace("\"", SEPARADOR).Replace("“", SEPARADOR).Replace(":", SEPARADOR).Replace("\r\n", SEPARADOR_ESPACO); 
        }
    }
}
